### ISSUE TITLE
Сломана игра 

### ISSUE THREAD

**Issue by chigriil** [dimon58/NeedForOtl10#14]
Опять поломана игра.

**Comment by chigriil** [comment]
Traceback (most recent call last):
  File "/Users/daniilcigrin/PycharmProjects/NeedForOtl10/main.py", line 28, in <module>
    app.run()
  File "/Users/daniilcigrin/PycharmProjects/NeedForOtl10/Engine/apps.py", line 147, in run
    raise e
  File "/Users/daniilcigrin/PycharmProjects/NeedForOtl10/Engine/apps.py", line 143, in run
    app = app.run()
  File "/Users/daniilcigrin/PycharmProjects/NeedForOtl10/Engine/apps.py", line 104, in run
    self.on_iteration()
  File "/Users/daniilcigrin/PycharmProjects/NeedForOtl10/Engine/gui/menu.py", line 158, in on_iteration
    self.customisationmenu.run()
  File "/Users/daniilcigrin/PycharmProjects/NeedForOtl10/Engine/apps.py", line 105, in run
    return self.atexit()
  File "/Users/daniilcigrin/PycharmProjects/NeedForOtl10/Engine/gui/menu.py", line 255, in atexit
    return Game(self.screen, self.clock, self.name_input.username).run()
  File "/Users/daniilcigrin/PycharmProjects/NeedForOtl10/src/game.py", line 143, in __init__
    self.scene.load_level(username)
  File "/Users/daniilcigrin/PycharmProjects/NeedForOtl10/Engine/Scene/gamescene.py", line 549, in load_level
    self.init_player(*data['MainCharacter']['vector'], **data['MainCharacter']['brain']['init'])
TypeError: string indices must be integers
